"""Add transcription model

Revision ID: 2561b9c2ebef
Revises: 
Create Date: 2025-05-25 17:09:42.882175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2561b9c2ebef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.alter_column('file_size',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('words', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('meta', sa.JSON(), nullable=True))
        batch_op.drop_column('raw_text')
        batch_op.drop_column('processed_text')
        batch_op.drop_column('confidence_score')

    with op.batch_alter_table('upload_sessions', schema=None) as batch_op:
        batch_op.alter_column('total_size',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_sessions', schema=None) as batch_op:
        batch_op.alter_column('total_size',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence_score', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('processed_text', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('raw_text', mysql.TEXT(), nullable=False))
        batch_op.drop_column('meta')
        batch_op.drop_column('words')
        batch_op.drop_column('text')

    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.alter_column('file_size',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False)

    # ### end Alembic commands ###
