"""add diarized_text to transcription model

Revision ID: 4fdf272cf418
Revises: 2561b9c2ebef
Create Date: 2025-05-25 17:36:41.128244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fdf272cf418'
down_revision = '2561b9c2ebef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diarized_text', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.drop_column('diarized_text')

    # ### end Alembic commands ###
