"""Add chunk_summaries table

Revision ID: 8ead7a53c8ff
Revises: 4fdf272cf418
Create Date: 2025-05-25 23:43:09.681938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ead7a53c8ff'
down_revision = '4fdf272cf418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soap_note_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['soap_note_id'], ['soap_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk_summaries')
    # ### end Alembic commands ###
